### ISSUE TITLE
Improved Docset

### ISSUE THREAD

**Issue by remko** [epitaphmike/draft-js-dash#1]
Hi there,

I noticed the Draft docset wasn't indexed properly (it couldn't find any of the functions i was looking for while developing), and that the split of the docs wasn't really done in a convenient way (i.e. not according to classes, components, properties, methods, functions, but rather just a direct mapping of the web pages).

Since I had some infrastructure for generating docsets lying around, I created an alternative docset (you can download a version here https://github.com/remko/draftjs-dash-generator/releases/download/v0.3.0alpha2/Draft.js.docset.zip ). It detects all the classes, components, methods, properties and classes, and indexes them appropriately, so they're very developer-friendly.

Would you mind if I submitted my version to Dash?

thanks,
Remko

**Comment by epitaphmike** [comment]
You are definitely right about that. Your indexing is much cleaner and a good model. I'll work on revising mine. I have no issue with you submitting your version. Great work.

**Comment by remko** [comment]
Great, thanks a lot!
